### ISSUE TITLE
Missing docs on filtering

### ISSUE THREAD

**Issue by jastBytes** [elimity-com/scim#137]
There is no documentation about how filtering is supposed to work with this library. There are things in internal, but that can't be used referencing the library since it is internal.

**Comment by di-wu** [comment]
Hi! 👋

> There is no documentation about how filtering is supposed to work with this library.

We try to provide a unopinionated implementation. The library does not include filtering since this is very dependent on the implementation of the SCIM server itself.

`f.e.` | The users and groups are stored in a SQL database, it would be much more efficient to write a custom [(SQL) transpiler*](https://github.com/articulate/scim-filter-transpiler) for that query language than to support general filtering based on native Go structures.
<sub><sup>(*) This is probably a little outdated.</sup></sub>

Every (filter) endpoint provides you with a tokenized filter that you can use.

> There are things in internal, but that can't be used referencing the library since it is internal.

The `internal` filter package is only used to parse/check filters and to support filtering on the schemas endpoint. It is not the goal to have it exported.

---

Let me know if you have any recommendations/feature requests.

**Comment by jastBytes** [comment]
I see! That makes totally sense. Thanks for explaining. I will see how to work with the tokenized filter. 👍
